export const PEOPLE_LIST_REQUEST = "PEOPLE_LIST_REQUEST";
export const PEOPLE_LIST_SUCCESS = "PEOPLE_LIST_SUCCESS";
export const PEOPLE_LIST_FAIL = "PEOPLE_LIST_FAIL";

export const PEOPLE_EDIT_REQUEST = "PEOPLE_EDIT_REQUEST";
export const PEOPLE_EDIT_SUCCESS = "PEOPLE_EDIT_SUCCESS";
export const PEOPLE_EDIT_FAIL = "PEOPLE_EDIT_FAIL";

export const PEOPLE_DELETE_REQUEST = "PEOPLE_DELETE_REQUEST";
export const PEOPLE_DELETE_SUCCESS = "PEOPLE_DELETE_SUCCESS";
export const PEOPLE_DELETE_FAIL = "PEOPLE_DELETE_FAIL";

export const PEOPLE_CREATE_REQUEST = "PEOPLE_CREATE_REQUEST";
export const PEOPLE_CREATE_SUCCESS = "PEOPLE_CREATE_SUCCESS";
export const PEOPLE_CREATE_FAIL = "PEOPLE_CREATE_FAIL";
export const PEOPLE_CREATE_RESET = "PEOPLE_CREATE_RESET";

export const PEOPLE_UPDATE_REQUEST = "PEOPLE_UPDATE_REQUEST";
export const PEOPLE_UPDATE_SUCCESS = "PEOPLE_UPDATE_SUCCESS";
export const PEOPLE_UPDATE_FAIL = "PEOPLE_UPDATE_FAIL";
export const PEOPLE_UPDATE_RESET = "PEOPLE_UPDATE_RESET";
